### ISSUE TITLE
OPEN DISCUSSION: TO-DO List for t/prog

### ISSUE THREAD

**Issue by vmfunc** [transcendentprogressivism/manifesto#3]

**Comment by vmfunc** [comment]
- [ ] we need to figure out a way to validate manifesto changes on PRs
- [ ] we need to add a new font and redesign the site a little bit
- [ ] we need to make a proper logo

any other suggestions?

**Comment by vmfunc** [comment]
we might want to establish a council to validate most manifesto changes, then pass those through a public vote

**Comment by ghost** [comment]
Current things I can think of. 

- [ ] The manifesto needs a full proofread and lint if that hasn't been done already. 
- [ ] Automate converting the markdown readme to PDF, EPub (someone mentioned they wanted this), and the site (all can be done via GH actions as far as I'm concerned)

**Comment by melqtx** [comment]
> - [ ] we need to figure out a way to validate manifesto changes on PRs
> - [ ] we need to add a new font and redesign the site a little bit
> - [ ] we need to make a proper logo
> - [ ] replace the default astros template 
> any other suggestions?

**Comment by vmfunc** [comment]
> Current things I can think of.
> 
> * [ ]  The manifesto needs a full proofread and lint if that hasn't been done already.
> * [ ]  Automate converting the markdown readme to PDF, EPub (someone mentioned they wanted this), and the site (all can be done via GH actions as far as I'm concerned)

Automating to PDF would be really useful, for the site, we already use a git submodule so it builds on the fly

**Comment by melqtx** [comment]
should we translate the manifesto into multiple languages, to target more people?

**Comment by vmfunc** [comment]
> should we translate the manifesto into multiple languages, to target more people?

Definitely

**Comment by ldecampo** [comment]
> we might want to establish a council to validate most manifesto changes, then pass those through a public vote

I definitely agree with this, making sure the manifesto accurately represents our beliefs should be top priority. I think having a delegation check changes first and then a public vote is a good idea.

**Comment by ghost** [comment]
> should we translate the manifesto into multiple languages, to target more people?

There is a tool out there to manage these but I'm blanking on the name.

**Comment by ghost** [comment]
> > should we translate the manifesto into multiple languages, to target more people?
> 
> There is a tool out there to manage these but I'm blanking on the name.

Weblate. Upon googling it tho doesn't seem like it'll work all that well for what we are doing :/

**Comment by TessavWalstijn** [comment]
> > should we translate the manifesto into multiple languages, to target more people?
> 
> There is a tool out there to manage these but I'm blanking on the name.

I think translation by community is more powerful and accurate then using a tool. 

(saying it as a bilingual who experiences generated translations when using websites in my native language)

**Comment by ldecampo** [comment]
> > > should we translate the manifesto into multiple languages, to target more people?
> > 
> > 
> > There is a tool out there to manage these but I'm blanking on the name.
> 
> I think translation by community is more powerful and accurate then using a tool.
> 
> (saying it as a bilingual who experiences generated translations when using websites in my native language)

If we have enough people/support community translation shouldn't be too hard. It'll also definitely be more accurate, I agree.

**Comment by ldecampo** [comment]
I also think at some point, once the manifesto is fleshed out and we have our feet under us, we host a seminar where we explain who we are and what the manifesto is saying, and then answer questions. It'd help spread awareness, help people get some questions answered, and probably get a bunch of people on board.

**Comment by vmfunc** [comment]
I believe we should maybe re-write the first part of the manifesto and focus more on decentralized governance directly through the intro. We should make it easy to digest at first then delve down into the details

**Comment by vikingSec** [comment]
> I also think at some point, once the manifesto is fleshed out and we have our feet under us, we host a seminar where we explain who we are and what the manifesto is saying, and then answer questions. It'd help spread awareness, help people get some questions answered, and probably get a bunch of people on board.

I watched something similar happen when I briefly engaged with the US Pirate Party. There were several brainstorming sessions where national and state chapters figured out what their core belief structures would be. It was very empowering and got a lot of folks on board and lead to some great discussion.
